<?php

/**
 * BaseMultimedia_Imagen
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property bigint $publicacion_id
 * @property string $imagen
 * @property string $pie
 * @property Publicacion $Publicacion
 * 
 * @method bigint            getPublicacionId()  Returns the current record's "publicacion_id" value
 * @method string            getImagen()         Returns the current record's "imagen" value
 * @method string            getPie()            Returns the current record's "pie" value
 * @method Publicacion       getPublicacion()    Returns the current record's "Publicacion" value
 * @method Multimedia_Imagen setPublicacionId()  Sets the current record's "publicacion_id" value
 * @method Multimedia_Imagen setImagen()         Sets the current record's "imagen" value
 * @method Multimedia_Imagen setPie()            Sets the current record's "pie" value
 * @method Multimedia_Imagen setPublicacion()    Sets the current record's "Publicacion" value
 * 
 * @package    hayequiposf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMultimedia_Imagen extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('multimedia__imagen');
        $this->hasColumn('publicacion_id', 'bigint', 8, array(
             'type' => 'bigint',
             'length' => 8,
             ));
        $this->hasColumn('imagen', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 30,
             ));
        $this->hasColumn('pie', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Publicacion', array(
             'local' => 'publicacion_id',
             'foreign' => 'id'));
    }
}