<?php

/**
 * BaseJugador_Partido
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property bigint $jugador_id
 * @property bigint $estado_jugador_id
 * @property bigint $equipo_id
 * @property int $dorsal
 * @property bigint $tactica_posicion_id
 * @property int $goles
 * @property int $amarillas
 * @property int $rojas
 * @property int $puntaje
 * @property string $comentario
 * @property Estado_Jugador $Estado_Jugador
 * @property Tactica_Posicion $Tactica_Posicion
 * @property Equipo_Partido $Equipo_Partido
 * @property Jugador $Jugador
 * @property Doctrine_Collection $Partido
 * 
 * @method bigint              getJugadorId()           Returns the current record's "jugador_id" value
 * @method bigint              getEstadoJugadorId()     Returns the current record's "estado_jugador_id" value
 * @method bigint              getEquipoId()            Returns the current record's "equipo_id" value
 * @method int                 getDorsal()              Returns the current record's "dorsal" value
 * @method bigint              getTacticaPosicionId()   Returns the current record's "tactica_posicion_id" value
 * @method int                 getGoles()               Returns the current record's "goles" value
 * @method int                 getAmarillas()           Returns the current record's "amarillas" value
 * @method int                 getRojas()               Returns the current record's "rojas" value
 * @method int                 getPuntaje()             Returns the current record's "puntaje" value
 * @method string              getComentario()          Returns the current record's "comentario" value
 * @method Estado_Jugador      getEstadoJugador()       Returns the current record's "Estado_Jugador" value
 * @method Tactica_Posicion    getTacticaPosicion()     Returns the current record's "Tactica_Posicion" value
 * @method Equipo_Partido      getEquipoPartido()       Returns the current record's "Equipo_Partido" value
 * @method Jugador             getJugador()             Returns the current record's "Jugador" value
 * @method Doctrine_Collection getPartido()             Returns the current record's "Partido" collection
 * @method Jugador_Partido     setJugadorId()           Sets the current record's "jugador_id" value
 * @method Jugador_Partido     setEstadoJugadorId()     Sets the current record's "estado_jugador_id" value
 * @method Jugador_Partido     setEquipoId()            Sets the current record's "equipo_id" value
 * @method Jugador_Partido     setDorsal()              Sets the current record's "dorsal" value
 * @method Jugador_Partido     setTacticaPosicionId()   Sets the current record's "tactica_posicion_id" value
 * @method Jugador_Partido     setGoles()               Sets the current record's "goles" value
 * @method Jugador_Partido     setAmarillas()           Sets the current record's "amarillas" value
 * @method Jugador_Partido     setRojas()               Sets the current record's "rojas" value
 * @method Jugador_Partido     setPuntaje()             Sets the current record's "puntaje" value
 * @method Jugador_Partido     setComentario()          Sets the current record's "comentario" value
 * @method Jugador_Partido     setEstadoJugador()       Sets the current record's "Estado_Jugador" value
 * @method Jugador_Partido     setTacticaPosicion()     Sets the current record's "Tactica_Posicion" value
 * @method Jugador_Partido     setEquipoPartido()       Sets the current record's "Equipo_Partido" value
 * @method Jugador_Partido     setJugador()             Sets the current record's "Jugador" value
 * @method Jugador_Partido     setPartido()             Sets the current record's "Partido" collection
 * 
 * @package    hayequiposf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJugador_Partido extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('jugador__partido');
        $this->hasColumn('jugador_id', 'bigint', 8, array(
             'type' => 'bigint',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('estado_jugador_id', 'bigint', 8, array(
             'type' => 'bigint',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('equipo_id', 'bigint', 8, array(
             'type' => 'bigint',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('dorsal', 'int', null, array(
             'type' => 'int',
             ));
        $this->hasColumn('tactica_posicion_id', 'bigint', 8, array(
             'type' => 'bigint',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('goles', 'int', null, array(
             'type' => 'int',
             ));
        $this->hasColumn('amarillas', 'int', null, array(
             'type' => 'int',
             ));
        $this->hasColumn('rojas', 'int', null, array(
             'type' => 'int',
             ));
        $this->hasColumn('puntaje', 'int', null, array(
             'type' => 'int',
             ));
        $this->hasColumn('comentario', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Estado_Jugador', array(
             'local' => 'estado_jugador_id',
             'foreign' => 'id'));

        $this->hasOne('Tactica_Posicion', array(
             'local' => 'tactica_posicion_id',
             'foreign' => 'id'));

        $this->hasOne('Equipo_Partido', array(
             'local' => 'equipo_id',
             'foreign' => 'id'));

        $this->hasOne('Jugador', array(
             'local' => 'jugador_id',
             'foreign' => 'id'));

        $this->hasMany('Partido', array(
             'local' => 'id',
             'foreign' => 'figura_id'));
    }
}