<?php

/**
 * BasePosicion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $abreviatura
 * @property string $descripcion
 * @property Doctrine_Collection $Tactica_Posicion
 * 
 * @method string              getAbreviatura()      Returns the current record's "abreviatura" value
 * @method string              getDescripcion()      Returns the current record's "descripcion" value
 * @method Doctrine_Collection getTacticaPosicion()  Returns the current record's "Tactica_Posicion" collection
 * @method Posicion            setAbreviatura()      Sets the current record's "abreviatura" value
 * @method Posicion            setDescripcion()      Sets the current record's "descripcion" value
 * @method Posicion            setTacticaPosicion()  Sets the current record's "Tactica_Posicion" collection
 * 
 * @package    hayequiposf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePosicion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('posicion');
        $this->hasColumn('abreviatura', 'string', 3, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 3,
             ));
        $this->hasColumn('descripcion', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 30,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Tactica_Posicion', array(
             'local' => 'id',
             'foreign' => 'posicion_id'));
    }
}