<?php

/**
 * BasePublicacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property bigint $jugador_id
 * @property string $contenido
 * @property Jugador $Jugador
 * @property Doctrine_Collection $Multimedia_Imagen
 * @property Doctrine_Collection $Multimedia_Video
 * 
 * @method bigint              getJugadorId()         Returns the current record's "jugador_id" value
 * @method string              getContenido()         Returns the current record's "contenido" value
 * @method Jugador             getJugador()           Returns the current record's "Jugador" value
 * @method Doctrine_Collection getMultimediaImagen()  Returns the current record's "Multimedia_Imagen" collection
 * @method Doctrine_Collection getMultimediaVideo()   Returns the current record's "Multimedia_Video" collection
 * @method Publicacion         setJugadorId()         Sets the current record's "jugador_id" value
 * @method Publicacion         setContenido()         Sets the current record's "contenido" value
 * @method Publicacion         setJugador()           Sets the current record's "Jugador" value
 * @method Publicacion         setMultimediaImagen()  Sets the current record's "Multimedia_Imagen" collection
 * @method Publicacion         setMultimediaVideo()   Sets the current record's "Multimedia_Video" collection
 * 
 * @package    hayequiposf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePublicacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('publicacion');
        $this->hasColumn('jugador_id', 'bigint', 8, array(
             'type' => 'bigint',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('contenido', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Jugador', array(
             'local' => 'jugador_id',
             'foreign' => 'id'));

        $this->hasMany('Multimedia_Imagen', array(
             'local' => 'id',
             'foreign' => 'publicacion_id'));

        $this->hasMany('Multimedia_Video', array(
             'local' => 'id',
             'foreign' => 'publicacion_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}