<?php

/**
 * BaseHistoria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property bigint $sujeto_id
 * @property bigint $tipo_historia_id
 * @property bigint $param1
 * @property bigint $param2
 * @property bigint $param3
 * @property bigint $param4
 * @property bigint $param5
 * @property Jugador $Jugador
 * @property Tipo_Historia $Tipo_Historia
 * 
 * @method bigint        getSujetoId()         Returns the current record's "sujeto_id" value
 * @method bigint        getTipoHistoriaId()   Returns the current record's "tipo_historia_id" value
 * @method bigint        getParam1()           Returns the current record's "param1" value
 * @method bigint        getParam2()           Returns the current record's "param2" value
 * @method bigint        getParam3()           Returns the current record's "param3" value
 * @method bigint        getParam4()           Returns the current record's "param4" value
 * @method bigint        getParam5()           Returns the current record's "param5" value
 * @method Jugador       getJugador()          Returns the current record's "Jugador" value
 * @method Tipo_Historia getTipoHistoria()     Returns the current record's "Tipo_Historia" value
 * @method Historia      setSujetoId()         Sets the current record's "sujeto_id" value
 * @method Historia      setTipoHistoriaId()   Sets the current record's "tipo_historia_id" value
 * @method Historia      setParam1()           Sets the current record's "param1" value
 * @method Historia      setParam2()           Sets the current record's "param2" value
 * @method Historia      setParam3()           Sets the current record's "param3" value
 * @method Historia      setParam4()           Sets the current record's "param4" value
 * @method Historia      setParam5()           Sets the current record's "param5" value
 * @method Historia      setJugador()          Sets the current record's "Jugador" value
 * @method Historia      setTipoHistoria()     Sets the current record's "Tipo_Historia" value
 * 
 * @package    hayequiposf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHistoria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('historia');
        $this->hasColumn('sujeto_id', 'bigint', 8, array(
             'type' => 'bigint',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('tipo_historia_id', 'bigint', 8, array(
             'type' => 'bigint',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('param1', 'bigint', 8, array(
             'type' => 'bigint',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('param2', 'bigint', 8, array(
             'type' => 'bigint',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('param3', 'bigint', 8, array(
             'type' => 'bigint',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('param4', 'bigint', 8, array(
             'type' => 'bigint',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('param5', 'bigint', 8, array(
             'type' => 'bigint',
             'notnull' => true,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Jugador', array(
             'local' => 'sujeto_id',
             'foreign' => 'id'));

        $this->hasOne('Tipo_Historia', array(
             'local' => 'tipo_historia_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}