<?php

/**
 * BaseEstado_Partido
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $descripcion
 * @property Doctrine_Collection $Partido
 * 
 * @method string              getNombre()      Returns the current record's "nombre" value
 * @method string              getDescripcion() Returns the current record's "descripcion" value
 * @method Doctrine_Collection getPartido()     Returns the current record's "Partido" collection
 * @method Estado_Partido      setNombre()      Sets the current record's "nombre" value
 * @method Estado_Partido      setDescripcion() Sets the current record's "descripcion" value
 * @method Estado_Partido      setPartido()     Sets the current record's "Partido" collection
 * 
 * @package    hayequiposf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstado_Partido extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estado__partido');
        $this->hasColumn('nombre', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 30,
             ));
        $this->hasColumn('descripcion', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Partido', array(
             'local' => 'id',
             'foreign' => 'estado_partido_id'));
    }
}