<?php

/**
 * BaseEquipo_Partido
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property bigint $partido_id
 * @property bigint $tactica_id
 * @property Tactica $Tactica
 * @property Partido $Partido
 * @property Doctrine_Collection $Jugadores
 * 
 * @method string              getNombre()     Returns the current record's "nombre" value
 * @method bigint              getPartidoId()  Returns the current record's "partido_id" value
 * @method bigint              getTacticaId()  Returns the current record's "tactica_id" value
 * @method Tactica             getTactica()    Returns the current record's "Tactica" value
 * @method Partido             getPartido()    Returns the current record's "Partido" value
 * @method Doctrine_Collection getJugadores()  Returns the current record's "Jugadores" collection
 * @method Equipo_Partido      setNombre()     Sets the current record's "nombre" value
 * @method Equipo_Partido      setPartidoId()  Sets the current record's "partido_id" value
 * @method Equipo_Partido      setTacticaId()  Sets the current record's "tactica_id" value
 * @method Equipo_Partido      setTactica()    Sets the current record's "Tactica" value
 * @method Equipo_Partido      setPartido()    Sets the current record's "Partido" value
 * @method Equipo_Partido      setJugadores()  Sets the current record's "Jugadores" collection
 * 
 * @package    hayequiposf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEquipo_Partido extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('equipo__partido');
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('partido_id', 'bigint', 8, array(
             'type' => 'bigint',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('tactica_id', 'bigint', 8, array(
             'type' => 'bigint',
             'notnull' => true,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tactica', array(
             'local' => 'tactica_id',
             'foreign' => 'id'));

        $this->hasOne('Partido', array(
             'local' => 'partido_id',
             'foreign' => 'id'));

        $this->hasMany('Jugador_Partido as Jugadores', array(
             'local' => 'id',
             'foreign' => 'equipo_id'));
    }
}