<?php

/**
 * BaseJugador_Ficha
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * 
 * @package    hayequiposf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJugador_Ficha extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('jugador__ficha');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}