<?php

/**
 * BasePartido
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property bigint $creador_id
 * @property date $fecha_creado
 * @property bigint $estado_partido_id
 * @property date $fecha_partido
 * @property string $comentarios
 * @property bigint $figura_id
 * @property Jugador $Jugador
 * @property Estado_Partido $Estado_Partido
 * @property Jugador_Partido $Jugador_Partido
 * @property Doctrine_Collection $Equipos
 * 
 * @method bigint              getCreadorId()         Returns the current record's "creador_id" value
 * @method date                getFechaCreado()       Returns the current record's "fecha_creado" value
 * @method bigint              getEstadoPartidoId()   Returns the current record's "estado_partido_id" value
 * @method date                getFechaPartido()      Returns the current record's "fecha_partido" value
 * @method string              getComentarios()       Returns the current record's "comentarios" value
 * @method bigint              getFiguraId()          Returns the current record's "figura_id" value
 * @method Jugador             getJugador()           Returns the current record's "Jugador" value
 * @method Estado_Partido      getEstadoPartido()     Returns the current record's "Estado_Partido" value
 * @method Jugador_Partido     getJugadorPartido()    Returns the current record's "Jugador_Partido" value
 * @method Doctrine_Collection getEquipos()           Returns the current record's "Equipos" collection
 * @method Partido             setCreadorId()         Sets the current record's "creador_id" value
 * @method Partido             setFechaCreado()       Sets the current record's "fecha_creado" value
 * @method Partido             setEstadoPartidoId()   Sets the current record's "estado_partido_id" value
 * @method Partido             setFechaPartido()      Sets the current record's "fecha_partido" value
 * @method Partido             setComentarios()       Sets the current record's "comentarios" value
 * @method Partido             setFiguraId()          Sets the current record's "figura_id" value
 * @method Partido             setJugador()           Sets the current record's "Jugador" value
 * @method Partido             setEstadoPartido()     Sets the current record's "Estado_Partido" value
 * @method Partido             setJugadorPartido()    Sets the current record's "Jugador_Partido" value
 * @method Partido             setEquipos()           Sets the current record's "Equipos" collection
 * 
 * @package    hayequiposf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePartido extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('partido');
        $this->hasColumn('creador_id', 'bigint', 8, array(
             'type' => 'bigint',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('fecha_creado', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('estado_partido_id', 'bigint', 8, array(
             'type' => 'bigint',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('fecha_partido', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('comentarios', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('figura_id', 'bigint', 8, array(
             'type' => 'bigint',
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Jugador', array(
             'local' => 'creador_id',
             'foreign' => 'id'));

        $this->hasOne('Estado_Partido', array(
             'local' => 'estado_partido_id',
             'foreign' => 'id'));

        $this->hasOne('Jugador_Partido', array(
             'local' => 'figura_id',
             'foreign' => 'id'));

        $this->hasMany('Equipo_Partido as Equipos', array(
             'local' => 'id',
             'foreign' => 'partido_id'));
    }
}