<?php

/**
 * BaseJugador
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $apellido
 * @property string $nombre
 * @property date $fecha_nacimiento
 * @property bigint $localidad_id
 * @property string $sexo
 * @property bigint $user_id
 * @property string $apodo
 * @property string $imagen
 * @property int $dorsal
 * @property Doctrine_Collection $Localidad
 * @property sfGuardUser $User
 * @property Doctrine_Collection $Partido
 * @property Doctrine_Collection $Historia
 * @property Doctrine_Collection $Publicacion
 * 
 * @method string              getApellido()         Returns the current record's "apellido" value
 * @method string              getNombre()           Returns the current record's "nombre" value
 * @method date                getFechaNacimiento()  Returns the current record's "fecha_nacimiento" value
 * @method bigint              getLocalidadId()      Returns the current record's "localidad_id" value
 * @method string              getSexo()             Returns the current record's "sexo" value
 * @method bigint              getUserId()           Returns the current record's "user_id" value
 * @method string              getApodo()            Returns the current record's "apodo" value
 * @method string              getImagen()           Returns the current record's "imagen" value
 * @method int                 getDorsal()           Returns the current record's "dorsal" value
 * @method Doctrine_Collection getLocalidad()        Returns the current record's "Localidad" collection
 * @method sfGuardUser         getUser()             Returns the current record's "User" value
 * @method Doctrine_Collection getPartido()          Returns the current record's "Partido" collection
 * @method Doctrine_Collection getHistoria()         Returns the current record's "Historia" collection
 * @method Doctrine_Collection getPublicacion()      Returns the current record's "Publicacion" collection
 * @method Jugador             setApellido()         Sets the current record's "apellido" value
 * @method Jugador             setNombre()           Sets the current record's "nombre" value
 * @method Jugador             setFechaNacimiento()  Sets the current record's "fecha_nacimiento" value
 * @method Jugador             setLocalidadId()      Sets the current record's "localidad_id" value
 * @method Jugador             setSexo()             Sets the current record's "sexo" value
 * @method Jugador             setUserId()           Sets the current record's "user_id" value
 * @method Jugador             setApodo()            Sets the current record's "apodo" value
 * @method Jugador             setImagen()           Sets the current record's "imagen" value
 * @method Jugador             setDorsal()           Sets the current record's "dorsal" value
 * @method Jugador             setLocalidad()        Sets the current record's "Localidad" collection
 * @method Jugador             setUser()             Sets the current record's "User" value
 * @method Jugador             setPartido()          Sets the current record's "Partido" collection
 * @method Jugador             setHistoria()         Sets the current record's "Historia" collection
 * @method Jugador             setPublicacion()      Sets the current record's "Publicacion" collection
 * 
 * @package    hayequiposf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJugador extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('jugador');
        $this->hasColumn('apellido', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('fecha_nacimiento', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('localidad_id', 'bigint', 8, array(
             'type' => 'bigint',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('sexo', 'string', 1, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('user_id', 'bigint', 8, array(
             'type' => 'bigint',
             'length' => 8,
             ));
        $this->hasColumn('apodo', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('imagen', 'string', 100, array(
             'type' => 'string',
             'default' => '0.jpg',
             'length' => 100,
             ));
        $this->hasColumn('dorsal', 'int', 3, array(
             'type' => 'int',
             'default' => 0,
             'length' => 3,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Localidad', array(
             'local' => 'localidad_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasMany('Partido', array(
             'local' => 'id',
             'foreign' => 'creador_id'));

        $this->hasMany('Historia', array(
             'local' => 'id',
             'foreign' => 'sujeto_id'));

        $this->hasMany('Publicacion', array(
             'local' => 'id',
             'foreign' => 'jugador_id'));
    }
}