<?php

/**
 * BaseEstado_Jugador
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $descripcion
 * @property Doctrine_Collection $Jugador_Partido
 * 
 * @method string              getNombre()          Returns the current record's "nombre" value
 * @method string              getDescripcion()     Returns the current record's "descripcion" value
 * @method Doctrine_Collection getJugadorPartido()  Returns the current record's "Jugador_Partido" collection
 * @method Estado_Jugador      setNombre()          Sets the current record's "nombre" value
 * @method Estado_Jugador      setDescripcion()     Sets the current record's "descripcion" value
 * @method Estado_Jugador      setJugadorPartido()  Sets the current record's "Jugador_Partido" collection
 * 
 * @package    hayequiposf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstado_Jugador extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estado__jugador');
        $this->hasColumn('nombre', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 30,
             ));
        $this->hasColumn('descripcion', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Jugador_Partido', array(
             'local' => 'id',
             'foreign' => 'estado_jugador_id'));
    }
}