<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/10/28 22:03:53

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=hayequipo',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
