<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/10/28 22:04:03
sfConfig::add(array(
  'mod_sfguardregister_enabled' => true,
  'mod_sfguardregister_view_class' => 'sfPHP',
));
