<?php

/**
 * Equipo_PartidoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Equipo_PartidoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Equipo_PartidoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Equipo_Partido');
    }
}