<?php

/**
 * Estado_PartidoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Estado_PartidoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Estado_PartidoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Estado_Partido');
    }
}