<?php

/**
 * Estado_JugadorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Estado_JugadorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Estado_JugadorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Estado_Jugador');
    }
}