<?php

/**
 * HistoriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HistoriaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HistoriaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Historia');
    }
    
    public static function getUltimas()
    {
        $ultimas = Doctrine_Query::create()
                ->select('h.id,h.tipo_historia_id,h.param1')
                ->from('Historia h')
                ->orderBy('h.updated_at DESC')
                ->limit(20)
                ->fetchArray();
        
        return $ultimas;

        
    }
}