<?php

/**
 * Jugador_PartidoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Jugador_PartidoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Jugador_PartidoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Jugador_Partido');
    }
}