<?php

/**
 * Jugador_FichaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Jugador_FichaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Jugador_FichaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Jugador_Ficha');
    }
}