<?php

/**
 * Multimedia_ImagenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Multimedia_ImagenTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Multimedia_ImagenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Multimedia_Imagen');
    }
}