<?php

/**
 * Multimedia_VideoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Multimedia_VideoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Multimedia_VideoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Multimedia_Video');
    }
}