<?php

/**
 * TacticaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TacticaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TacticaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tactica');
    }
}