<?php

/**
 * Tactica_PosicionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Tactica_PosicionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Tactica_PosicionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tactica_Posicion');
    }
}