<?php

/**
 * Tipo_HistoriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Tipo_HistoriaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Tipo_HistoriaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tipo_Historia');
    }
}