# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View
default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css,jquery.mCustomScrollbar.css]

  javascripts:    [jquery.js,mocha.js,jquery.mousewheel.min.js,jquery.mCustomScrollbar.js]

  has_layout:     true
  layout:         layout
  

