<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/10/27 06:55:51

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=hayequiposf',
  'username' => 'JuanD',
  'password' => 'kakilo',
  'name' => 'doctrine',
)),);
